version: "3"
services:
  postgres:
    container_name: st_booker_postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bookings
    ports:
      - "5432:5432"
  server:
    container_name: st_booker
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
